sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
build:
  runnerOs: ubuntu-24.04
  freeDiskSpace: true
  exasolDbVersions:
    - "8.29.9" # Still not adapted to TS precision. See https://github.com/exasol/hana-virtual-schema/issues/40
  # - "7.1.30" # Exasol 7.1.x does not yet support the latest Ubuntu version
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Fix VM Crash in UDFs
            id: fix-vm-crash
            run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
