sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: true
  exasolDbVersions:
    - "7.1.25"
    - "8.24.0"
linkReplacements:
